services:
  kafka:
    image: bitnami/kafka:latest
    container_name: services
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_PORT: 9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://services:9092
      KAFKA_LISTENER_NAMES: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_KRAFT_MODE: "true"
    volumes:
      - ./kafka/data:/bitnami/kafka

  #authgrpc:
    #build:
      #context: .
      #dockerfile: ./authService/Dockerfile
    #ports:
      #- "44044:44044"
    #volumes:
      #- ./authService/config:/app/config
    #depends_on:
      #- postgresdb
  #postgresdb:
    #restart: always
    #image: postgres:latest
    #volumes:
      #- ./.database/postgres/data:/var/lib/postgresql/data
    #environment:
      #POSTGRES_USER: "postgres"
      #POSTGRES_PASSWORD: "1111"
      #POSTGRES_DB: "authDB"
    #ports:
      #- "5436:5432"
