services:
  zookeeper:
    image : confluentinc/cp-zookeeper:7.7.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000


  kafka1:
    image: confluentinc/cp-server:latest
    hostname: kafka1
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9020:8080
    environment:
      AUTH_TYPE: DISABLED
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka1


  #authgrpc:
    #build:
      #context: .
      #dockerfile: ./authService/Dockerfile
    #ports:
      #- "44044:44044"
    #volumes:
      #- ./authService/config:/app/config
    #depends_on:
      #- postgresdb
  #postgresdb:
    #restart: always
    #image: postgres:latest
    #volumes:
      #- ./.database/postgres/data:/var/lib/postgresql/data
    #environment:
      #POSTGRES_USER: "postgres"
      #POSTGRES_PASSWORD: "1111"
      #POSTGRES_DB: "authDB"
    #ports:
      #- "5436:5432"
