version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "44048:44048"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "44049:44049"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:44048
  authgrpc:
    build:
      context: .
      dockerfile: ./deepLink/Dockerfile
    ports:
      - "44044:44044"
    volumes:
      - ./deepLink/config:/app/config
    depends_on:
      - postgresdb
  postgresdb:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1111"
      POSTGRES_DB: "authDB"
    ports:
      - "5436:5432"
